// generated by sim/test_cap.py -- do not edit
localparam integer N_SPI_CAP = 11;
localparam integer SPI_CAP_BITS = 8;
localparam [15:0] SPI_CAP_TX = 16'h00A5;
reg [15:0] SPI_CAP_IMEM [0:10];
initial SPI_CAP_IMEM[0] = 16'hE063;
initial SPI_CAP_IMEM[1] = 16'hE0A1;
initial SPI_CAP_IMEM[2] = 16'hE082;
initial SPI_CAP_IMEM[3] = 16'hE000;
initial SPI_CAP_IMEM[4] = 16'h80A0;
initial SPI_CAP_IMEM[5] = 16'hE027;
initial SPI_CAP_IMEM[6] = 16'h6001;
initial SPI_CAP_IMEM[7] = 16'h5001;
initial SPI_CAP_IMEM[8] = 16'h0046;
initial SPI_CAP_IMEM[9] = 16'h8000;
initial SPI_CAP_IMEM[10] = 16'h0004;
