"""Capture shadow vs RTL: 32 slots, hold-this, SCLK-mode JEDEC."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "sim"))
sys.path.insert(0, str(ROOT / "fw"))

from flash_miso import JEDEC_ID, FlashMiso  # noqa: E402
from golden import CAP_DEPTH, Core  # noqa: E402
import spi_jedec  # noqa: E402
import spi_master  # noqa: E402
import uart_tx  # noqa: E402

UART_STEPS = 48
SPI_STEPS = 80
JEDEC_STEPS = 160


def run_uart_cap(byte: int = 0x55) -> Core:
    c = Core()
    c.load(uart_tx.program())
    c.sm0.tx.append(byte)
    c.start0 = True
    c.cap_en = True
    c.uio_in = 1
    for _ in range(UART_STEPS):
        c.step()
    return c


def run_spi_cap(bits: int, word: int) -> Core:
    c = Core()
    c.load(spi_master.program(0, 0, bits=bits))
    c.sm0.tx.append(word)
    c.start0 = True
    c.cap_en = True
    c.uio_in = 0xFF
    for _ in range(SPI_STEPS):
        c.step()
    return c


def run_jedec_cap() -> Core:
    c = Core()
    c.load(spi_jedec.program())
    c.sm0.tx.append(spi_jedec.tx_word(0x9F))
    c.start0 = True
    c.cap_en = True
    c.cap_mode = 1
    flash = FlashMiso()
    for _ in range(JEDEC_STEPS):
        c.uio_in = (0xFF & ~4) | ((flash.miso & 1) << 2)
        resolved, _oe = c.step()
        flash.tick(resolved)
    return c


def mosi_on_sclk_rise(records: list[tuple[int, int, int]]) -> tuple[int, list[int]]:
    """LSB-first MOSI on SCLK 0->1 while MOSI+SCLK are driven. Not a timed tape."""
    prev_sclk = 0
    bits: list[int] = []
    for _hold, pins, oe in records:
        if (oe & 3) != 3:
            prev_sclk = (pins >> 1) & 1
            continue
        sclk = (pins >> 1) & 1
        mosi = pins & 1
        if prev_sclk == 0 and sclk == 1:
            bits.append(mosi)
        prev_sclk = sclk
    acc = 0
    for i, b in enumerate(bits):
        acc |= b << i
    return acc, bits


def jedec_id_from_sclk_records(records: list[tuple[int, int, int]]) -> tuple[int, ...]:
    bits: list[int] = []
    for _hold, pins, _oe in records:
        if ((pins >> 3) & 1) != 0:
            continue
        bits.append((pins >> 2) & 1)
    if len(bits) < 32:
        raise AssertionError(f"JEDEC SCLK samples {len(bits)} < 32")
    data = bits[8:32]
    out = []
    for i in range(0, 24, 8):
        acc = 0
        for b in data[i : i + 8]:
            acc = (acc << 1) | b
        out.append(acc)
    return tuple(out)


def hunt_spi_width() -> tuple[int, int, list[int]]:
    for n in range(8, 0, -1):
        mask = (1 << n) - 1
        word = 0xA5 & mask
        c = run_spi_cap(n, word)
        got, bitlist = mosi_on_sclk_rise(c.capture)
        if got == word and len(bitlist) == n:
            return n, got, bitlist
    raise AssertionError("no SPI mode-0 width with MOSI match")


def emit_uart_expect(path: Path, records: list[tuple[int, int, int]]) -> None:
    lines = [f"{len(records)}"]
    for hold, pins, oe in records:
        lines.append(f"{hold:d} {pins:02X} {oe:02X}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_uart_vh(path: Path, records: list[tuple[int, int, int]]) -> None:
    n = len(records)
    lines = ["// generated by sim/test_cap.py -- do not edit\n"]
    lines.append(f"localparam integer N_UART_CAP = {n};\n")
    lines.append(f"reg [7:0] UART_CAP_HOLD [0:{n - 1}];\n")
    lines.append(f"reg [7:0] UART_CAP_PIN [0:{n - 1}];\n")
    lines.append(f"reg [7:0] UART_CAP_OE [0:{n - 1}];\n")
    for i, (hold, pins, oe) in enumerate(records):
        lines.append(f"initial UART_CAP_HOLD[{i}] = 8'd{hold};\n")
        lines.append(f"initial UART_CAP_PIN[{i}] = 8'h{pins:02X};\n")
        lines.append(f"initial UART_CAP_OE[{i}] = 8'h{oe:02X};\n")
    path.write_text("".join(lines), encoding="utf-8")


def emit_spi_vh(path: Path, prog: list[int], bits: int, word: int) -> None:
    lines = ["// generated by sim/test_cap.py -- do not edit\n"]
    lines.append(f"localparam integer N_SPI_CAP = {len(prog)};\n")
    lines.append(f"localparam integer SPI_CAP_BITS = {bits};\n")
    lines.append(f"localparam [15:0] SPI_CAP_TX = 16'h{word:04X};\n")
    lines.append(f"reg [15:0] SPI_CAP_IMEM [0:{len(prog) - 1}];\n")
    for i, w in enumerate(prog):
        lines.append(f"initial SPI_CAP_IMEM[{i}] = 16'h{w:04X};\n")
    path.write_text("".join(lines), encoding="utf-8")


def emit_jedec_vh(path: Path, prog: list[int], records: list[tuple[int, int, int]]) -> None:
    lines = ["// generated by sim/test_cap.py -- do not edit\n"]
    lines.append(f"localparam integer N_JEDEC_IMEM = {len(prog)};\n")
    lines.append(f"localparam integer N_JEDEC_CAP = {len(records)};\n")
    lines.append(f"reg [15:0] JEDEC_CAP_IMEM [0:{len(prog) - 1}];\n")
    for i, w in enumerate(prog):
        lines.append(f"initial JEDEC_CAP_IMEM[{i}] = 16'h{w:04X};\n")
    path.write_text("".join(lines), encoding="utf-8")


def test_uart_cap() -> list[tuple[int, int, int]]:
    c = run_uart_cap(0x55)
    n = len(c.capture)
    if n == 0 or n > CAP_DEPTH:
        raise AssertionError(f"UART CAP wptr {n}")
    print(f"CAP UART 0x55 wptr={n}")
    return c.capture


def test_spi_cap_fit() -> tuple[int, int]:
    n, got, bitlist = hunt_spi_width()
    print(f"CAP SPI mode0 {n} MOSI={got:#x} bits={bitlist}")
    return n, got


def test_jedec_sclk_cap() -> list[tuple[int, int, int]]:
    c = run_jedec_cap()
    n = len(c.capture)
    if n != 32:
        raise AssertionError(f"JEDEC CAP wptr {n} != 32")
    got = jedec_id_from_sclk_records(c.capture)
    if got != JEDEC_ID:
        raise AssertionError(f"JEDEC CAP ID {got} != {JEDEC_ID}")
    print(f"CAP JEDEC 0x9F wptr={n} ID={got[0]:02X} {got[1]:02X} {got[2]:02X}")
    return c.capture


def test_uart_expand_still_holds() -> None:
    from test_all import expand_capture

    c = run_uart_cap(0x55)
    expanded = [p & 1 for p in expand_capture(c.capture)]
    data = [0] + [(0x55 >> i) & 1 for i in range(8)]
    if not any(expanded[i : i + 9] == data for i in range(max(0, len(expanded) - 8))):
        raise AssertionError(f"capture expand lost 0x55: {expanded}")


def main() -> None:
    rec = test_uart_cap()
    test_uart_expand_still_holds()
    n, got = test_spi_cap_fit()
    jedec_rec = test_jedec_sclk_cap()
    emit_uart_expect(ROOT / "sim" / "uart_cap.expect", rec)
    emit_uart_vh(ROOT / "test" / "uart_cap.vh", rec)
    word = 0xA5 & ((1 << n) - 1)
    emit_spi_vh(ROOT / "test" / "spi_cap.vh", spi_master.program(0, 0, bits=n), n, word)
    emit_jedec_vh(ROOT / "test" / "jedec_cap.vh", spi_jedec.program(), jedec_rec)
    Path(ROOT / "sim" / "spi_cap_fit.txt").write_text(f"{n} {got}\n", encoding="utf-8")


if __name__ == "__main__":
    main()
