"""USB LS bit-layer TX. Host encodes NRZI+stuff+CRC16; SM only serializes.

D- = pin0, D+ = pin1. Not a PHY, not a device, not HID. No NAK. No chirp.
FIFO words are PINOE beats, same job as i2c_master.encode_byte().
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "sim"))

from isa import jmp, out, pull, sett

ACK = 0xD2
DATA0 = 0xC3
SYNC = 0x80
J = 0b01
K = 0b10
SE0 = 0b00
OE_D = 0b11

PULL = 1


def pinoe_word(oe: int, val: int) -> int:
    return ((oe & 0xFF) << 8) | (val & 0xFF)


def crc16_usb(data: bytes) -> int:
    """CRC-16/USB: poly 0x8005 reflected, init/xorout 0xFFFF. Not linux/crc16.h."""
    crc = 0xFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0xA001 if crc & 1 else crc >> 1
    return crc ^ 0xFFFF


def stuff(nrz: list[int]) -> list[int]:
    """Insert 0 after six 1s, including a last bit before EOP. SYNC trailing 1 counts."""
    ones = 0
    out: list[int] = []
    for bit in nrz:
        if bit not in (0, 1):
            raise ValueError("nrz")
        out.append(bit)
        if bit:
            ones += 1
            if ones == 6:
                out.append(0)
                ones = 0
        else:
            ones = 0
    return out


def _bytes_to_nrz(body: list[int]) -> list[int]:
    bits: list[int] = []
    for byte in body:
        for i in range(8):
            bits.append((byte >> i) & 1)
    return bits


def encode_packet(pid: int, payload: bytes | None = None) -> list[int]:
    """SYNC 0x80, PID, optional payload+CRC16 LE, stuff, NRZI from idle J, EOP, HiZ.

    Handshake (payload is None): PID only, no CRC. Do not pass NAK.
    """
    pid &= 0xFF
    if pid == 0x5A:
        raise ValueError("host never NAKs")
    body = [SYNC, pid]
    if payload is not None:
        pl = bytes(payload)
        crc = crc16_usb(pl)
        body.extend(pl)
        body.append(crc & 0xFF)
        body.append((crc >> 8) & 0xFF)
    stuffed = stuff(_bytes_to_nrz(body))
    level = J
    words: list[int] = []
    for bit in stuffed:
        if bit == 0:
            level = K if level == J else J
        words.append(pinoe_word(OE_D, level))
    words.append(pinoe_word(OE_D, SE0))
    words.append(pinoe_word(OE_D, SE0))
    words.append(pinoe_word(OE_D, J))
    words.append(pinoe_word(0, 0))
    return words


def program() -> list[int]:
    # side_pin=7 so default side-set does not smash D+ on pin1 during PULL.
    return [
        sett(5, 7),
        pull(block=True),
        out(4, 0),
        jmp(PULL),
    ]


def emit_vh(path: str) -> None:
    pkts = (
        ("ACK", encode_packet(ACK)),
        ("D0FF", encode_packet(DATA0, b"\xFF")),
        ("D000", encode_packet(DATA0, b"\x00")),
    )
    lines = ["// generated by fw/usb_ls.py -- PINOE beats, do not edit\n"]
    for name, words in pkts:
        lines.append(f"localparam integer N_{name} = {len(words)};\n")
        lines.append(f"reg [15:0] PKT_{name} [0:{len(words) - 1}];\n")
        for i, w in enumerate(words):
            lines.append(f"initial PKT_{name}[{i}] = 16'h{w:04X};\n")
    Path(path).write_text("".join(lines), encoding="utf-8")


if __name__ == "__main__":
    import sys

    if len(sys.argv) >= 3 and sys.argv[1] == "--vh":
        emit_vh(sys.argv[2])
    else:
        for i, w in enumerate(program()):
            print(f"W{i:02d} = 16'h{w:04X}")
